version: "3"
services:
  conpot:
    container_name: PiPotTwo
    build: ./
    ports:
      - "80:8800" #SCADA UI, http
      - "102:10201" #S7Comm
      - "502:5020" #Modbus
      - "161:16100/udp" #SNMP
    restart: always
    logging:
      driver: "journald"
